### ISSUE TITLE
EPG & Season / Episode numbers

### ISSUE THREAD

**Issue by rtyk** [wouterdebie/locast2tuner#56]
Not sure if there is anything that can be done about this, but the epg.xml file from locast doesn't seem to contain any season and episode numbers that are usable by Emby.  I recently switched to m3u tuner and epg.xml and am no longer have the option to "record series" in emby.  Taking a closer look at the program information in emby guide, there are no season / episode numbers.  I'm not sure exactly what emby is looking for, but it doesn't seem to be provided by the locast file.  If there isn't anything that can be done about this, just let it serve as a caveat to other users.  

Example of program data from epg
`<programme start="20210524010000 +0000" stop="20210524020000 +0000" channel="channel.104"><title lang="en">NCIS: Los Angeles</title><desc lang="en">Deeks is kidnapped by an associate of Kirkin's who is in need of his help; NCIS investigates the shooting of a militarized dolphin equipped with a Russian microchip; Beale makes Nell an interesting offer.</desc><credits><director>John P. Kousakis</director><actor>Chris O'Donnell</actor><actor>LL Cool J</actor><actor>Linda Hunt</actor></credits><date>20210523</date><category lang="en">Crime drama</category><category lang="en">Action</category><category lang="en">Adventure</category><category lang="en">Mystery</category><category lang="en">Series</category><length units="seconds">3600</length><icon src="https://fans.tmsimg.com/assets/p18964076_b_v13_aa.jpg?w=240&amp;h=360" height="360" width="240"/><episode-num system="xmltv_ns">11.17.</episode-num><episode-num system="dd_progid">EP011583610288</episode-num><video><present>yes</present><aspect>16:9</aspect><quality>HDTV</quality></video><audio><present>yes</present><stereo>stereo</stereo></audio><new/><rating system="VCHIP"><value>TV14</value></rating></programme>`

**Comment by wouterdebie** [comment]
Strange.. Because the episode number is mentioned twice and seems according to XML-TV spec. I don't have a setup working right now, but I know @Croq360 always tests a lot. Maybe he can help?

**Comment by rtyk** [comment]
One other item came to mind.  I am using the latest Emby version 4.6.0.50 which was just released.  And I only made the change to the epg.xml after the upgrade was installed.  Haven't tested on an earlier version. Interested in what observations @Croq360 has made.

**Comment by eiddor** [comment]
Interesting - I'm seeing the same thing in Emby 4.6.0.50:

![image](https://user-images.githubusercontent.com/7586731/119413845-0f31f700-bcb4-11eb-9975-10f61b63663e.png)

Plex, however, does show the information:

![image](https://user-images.githubusercontent.com/7586731/119413880-1e18a980-bcb4-11eb-9bc0-7250548055e9.png)

**Comment by wouterdebie** [comment]
@eiddor thanks for checking.. do you think it's a regression in Emby?

**Comment by Croq360** [comment]
I see those too, but like @rtyk posted, something seems off.  If I click on the show in the guide, I only get the opportunity to record it a single time, no prompting to record the series, all episodes, new episodes, etc.

**Comment by wouterdebie** [comment]
There are some "fixes" around episode numbers in Emby: https://github.com/MediaBrowser/Emby.Releases/releases

**Comment by Croq360** [comment]
Note that the episode numbers are there.  In Plex, I see this:

![image](https://user-images.githubusercontent.com/25014870/119414776-130a4d00-bca5-11eb-92cd-d6857a21ab63.png)

**Comment by eiddor** [comment]
@eiddor So full disclosure, the only reason I subscribed to Locast and integrated it with Emby/Plex was to be able to contribute to the project to keep my Docker/Git skills current.  I don't actually watch TV haha.

This one seems relevant: "Support SXXEXX episode numbers in xml tv guide data"

**Comment by wouterdebie** [comment]
I just pushed 0.1.39, which is now building. I added SXXEXX as an additional format for `episod-num` in `epg.xml`. Would you mind testing in 15 mins when the binaries have been built?

**Comment by wouterdebie** [comment]
> I don't actually watch TV haha.

@eiddor Haha, pretty much the same here. Outside of NFL season I don't watch TV :) I do enjoy coding though :)

**Comment by wouterdebie** [comment]
Also, thanks @Croq360 for checking!

**Comment by rtyk** [comment]
I'll try updating to Emby 4.6.1.0 which was released a couple hours ago
"Fix regression in xmltv series identification"
[https://github.com/MediaBrowser/Emby.Releases/releases](url)

**Comment by eiddor** [comment]
@wouterdebie Latest locast2tuner didn't fix it - The LSIO Emby container hasn't updated yet, but I can test that tomorrow.

**Comment by Croq360** [comment]
I updated to latest Emby, no luck here.  Episode numbers still not showing up when you click on a show in the guide, and it's not offering to set up the show as a series recording.  Thinking about backtracking to an earlier version.

I do think this is more an Emby issue than a locast2tuner issue.

**Comment by wouterdebie** [comment]
Yeah, I think it's an Emby issue as well.. Seems like they messed up episode parsing.

**Comment by wouterdebie** [comment]
Just created a ticket: https://emby.media/community/index.php?/topic/98397-episode-information-not-working/

**Comment by rtyk** [comment]
I agree that it is likely an Emby issue.  I have just created an Emby test instance and will try to provide some detail for the ticket.

**Comment by rtyk** [comment]
I built a test system on Emby 4.6.1.0 and was unable to duplicate the problem after many combinations of other tuners and Emby provided epg.  I then upgraded my production Emby to 4.6.1.0 but the issue was still there.  I then removed the xml.epg from Emby, rebooted Emby, and then re-added the locast xml.epg.  After this all appears to be working.  My assumption is that the update to Emby resolved the problem, but required a purge of the existing epg data.

**Comment by wouterdebie** [comment]
@rtyk nice find! Emby does cache data quite a bit, so it makes sense that purging and re-adding the source works.

**Comment by eiddor** [comment]
I can confirm - For me, it fixed itself overnight by itself (no upgrade or changing the source.

![image](https://user-images.githubusercontent.com/7586731/119511431-0551d780-bd38-11eb-911c-20ca38e15fe6.png)

**Comment by Croq360** [comment]
Yeah, it seems that upgrading to 4.6.1.0 and having the EPG reload solved the issues I was seeing...

![image](https://user-images.githubusercontent.com/25014870/119512486-33c7b680-bd28-11eb-92f3-d6199281599f.png)

**Comment by rtyk** [comment]
This seems to be resolved.  I'm closing the issue.
